# Generated by Django 3.0.7 on 2021-05-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата обновления'),
        ),
    ]
