# Generated by Django 3.0.7 on 2021-05-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210502_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=150, unique=True, verbose_name='адрес'),
        ),
    ]
