# Generated by Django 3.0.7 on 2021-03-24 06:39

from django.db import migrations


def count_price_old_orders(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.all():
        item.price = item.quantity * item.product.price
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0039_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(count_price_old_orders),
    ]
