# Generated by Django 3.0.7 on 2021-03-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20210324_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Не обработан', 'Не обработан'), ('Обработан', 'Обработан')], default='Не обработан', max_length=15),
        ),
    ]
