# Generated by Django 3.0.7 on 2021-03-26 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Звонок произведен'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='order',
            name='registated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Заказ получен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Не обработан', 'Не обработан'), ('Обработан', 'Обработан')], default='Не обработан', max_length=15, verbose_name='Статус'),
        ),
    ]
