# Generated by Django 3.0.7 on 2021-04-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
