# Generated by Django 3.0.7 on 2021-05-02 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20210426_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Звонок произведен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Фактическое время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('no', 'Не обработан'), ('yes', 'Обработан')], db_index=True, default='no', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], db_index=True, max_length=15, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Заказ получен'),
        ),
    ]
